### ISSUE TITLE
Game crashing when picking up specific weapons

### ISSUE THREAD

**Issue by npfanman** [Sweenus/SimplySwords#170]
Soul Renderer, Hearthflame, Soulkeeper, Thunderbrand, and Flamewind crash game on immediate pickup. May be others that crash game as well. I am using mythic metals and better combat, among others. Also, I will update this list with more weapons as I test them.

**Comment by Sweenus** [comment]
Please attach your crashlog

Most likely, you are running incompatible versions of Simply Swords and Spell Power Attributes. Please update both of these mods to the latest

**Comment by VAlentA1M** [comment]
`net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find attribute null
        at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[server-intermediary.jar:?]
        at net.minecraft.class_5131.method_26852(class_5131.java:76) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[server-intermediary.jar:?]
        at net.spell_power.api.SpellSchools.lambda$configureAsMagic$0(SpellSchools.java:83) ~[spell_power-0.11.0+1.20.1.jar:?]
        at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.11.0+1.20.1.jar:?]
        at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.11.0+1.20.1.jar:?]
        at com.spellbladenext.Spellblades.lambda$onInitialize$2(Spellblades.java:300) ~[spellbladenext-1.17.2.jar:?]
        at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:116) ~[spell_power-0.11.0+1.20.1.jar:?]
        at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:97) ~[spell_power-0.11.0+1.20.1.jar:?]
        at net.sweenus.simplyswords.fabric.FabricHelperMethods.useSpellAttributeScaling(FabricHelperMethods.java:25) ~[simplyswords-1.55.0-1.20.1.jar:?]
        at net.sweenus.simplyswords.fabric.SimplySwordsExpectPlatformImpl.getSpellPowerDamage(SimplySwordsExpectPlatformImpl.java:19) ~[simplyswords-1.55.0-1.20.1.jar:?]
        at net.sweenus.simplyswords.SimplySwordsExpectPlatform.getSpellPowerDamage(SimplySwordsExpectPlatform.java) ~[simplyswords-1.55.0-1.20.1.jar:?]
        at net.sweenus.simplyswords.util.HelperMethods.commonSpellAttributeScaling(HelperMethods.java:508) ~[simplyswords-1.55.0-1.20.1.jar:?]
        at net.sweenus.simplyswords.item.custom.ThunderbrandSwordItem.method_7888(ThunderbrandSwordItem.java:99) ~[simplyswords-1.55.0-1.20.1.jar:?]
        at net.minecraft.class_1799.method_7917(class_1799.java:490) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:256) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
[12:37:02] [Server thread/INFO]: ValentAIM lost connection: Internal server error
[12:37:02] [Server thread/INFO]: ValentAIM left the game`
About the same problem only on the server side, in a single player game everything is fine(

**Comment by KleineFeder** [comment]
Hey, my Friends and I have the same problem with some unique Weapons. 

crash report here:
[message-1.txt](https://github.com/user-attachments/files/17504454/message-1.txt)
