### ISSUE TITLE
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simplyswords'!

### ISSUE THREAD

**Issue by RadDrew42** [Sweenus/SimplySwords#3]
the game keeps crashing every time I try to load with simplyswords *specifically,* I have tried getting rid of mods and nothing will fix the error.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/25/22, 9:00 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'simplyswords'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/loot/v2/LootTableEvents
	at net.sweenus.simplyswords.util.ModLootTableModifiers.modifyLootTables(ModLootTableModifiers.java:30)
	at net.sweenus.simplyswords.SimplySwords.onInitialize(SimplySwords.java:38)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.loot.v2.LootTableEvents
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more

**Comment by Sweenus** [comment]
Thanks for the report!

Do you have the Fabric API mod installed? https://www.curseforge.com/minecraft/mc-mods/fabric-api
This crash report looks like it's caused by trying to find the loot table method from Fabric API, and it not existing. You need to make sure that's installed.

**Comment by RadDrew42** [comment]
I have fabric api installed, but I'll try reinstalling it

**Comment by Sweenus** [comment]
No worries - if it's still crashing after a reinstall can you fetch me the full crash log?

**Comment by RadDrew42** [comment]
it's working now, turns out my version of fabric api was outdated and I didn't realize.
