### ISSUE TITLE
Simply Swords has failed to load correctly

### ISSUE THREAD

**Issue by MRVNTA** [Sweenus/SimplySwords#42]
I was testing  if a custom modpack i was working on, would run well on Mac and when i tried to start Minecraft the following error appeared:

(Already tried it with every modversion of 1.19.2)

-- Head --
Thread: Render thread
Stacktrace:
	at net.sweenus.simplyswords.SimplySwords.init(SimplySwords.java:44) ~[simplyswords-forge-1.43.0-1.19.2.jar%23351!/:?] {re:classloading}
-- MOD simplyswords --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23382!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23381!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File: /Users/kilianforberg/Desktop/AT Launcher/ATLauncher.app/Contents/Java/instances/Minecraft1192withForge/mods/simplyswords-forge-1.43.0-1.19.2.jar
	Failure message: Simply Swords (simplyswords) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 1.43.0-1.19.2
	Mod Issue URL: https://github.com/Sweenus/SimplySwords/issues
	Exception message: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "json" is null
Stacktrace:
	at net.sweenus.simplyswords.SimplySwords.init(SimplySwords.java:44) ~[simplyswords-forge-1.43.0-1.19.2.jar%23351!/:?] {re:classloading}
	at net.sweenus.simplyswords.forge.SimplySwordsForge.<init>(SimplySwordsForge.java:18) ~[simplyswords-forge-1.43.0-1.19.2.jar%23351!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {re:mixin}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23382!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23381!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Comment by Sweenus** [comment]
Hi there,

If you remove Simply Swords from the modpack and try to launch, does it boot correctly?

**Comment by MRVNTA** [comment]
Yes, without the mod everything loads as intended.

**Comment by Sweenus** [comment]
Thank you. Can I also ask if the crash ocurrs with only Simply Swords and its dependencies installed?

**Comment by KingQuak9000** [comment]
Hi there, I am also on a mac and on 1.18.2 and experiencing the same crash. Simplyswords failed to load correctly (null)
[crash-2023-02-25_02.57.23-fml.txt](https://github.com/Sweenus/SimplySwords/files/10828963/crash-2023-02-25_02.57.23-fml.txt)

**Comment by MRVNTA** [comment]
So, after test with only the mod with it dependency  i get the exact same error.

**Comment by Sweenus** [comment]
Are you able to try importing your modpack into the CurseForge launcher and testing it there?

I believe @Quakyytheduck mentioned on Discord that it was an issue with ATLauncher specifically, and that it worked fine in the CurseForge launcher.

**Comment by MRVNTA** [comment]
Indeed the ATLauncher was the problem all along, with the curselaunche the problem doesnt occur. Thank you for your troubleshooting.
